[workspace]
resolver = "3"
members = [
    "crates/pyo3-gated",
    "crates/pyo3-gated-macros",
    "examples/color-module",
    "tests/crates/plain-user",
    "tests/crates/python-user",
    "tests/crates/renamed-dep-user",
    "tests/crates/renamed-pyo3-user",
    "tests/crates/stub-user",
]

[workspace.package]
edition = "2024"
rust-version = "1.90"
license = "MIT"
repository = "https://github.com/giddyos/pyo3-gated"
homepage = "https://github.com/giddyos/pyo3-gated"

[workspace.dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
proc-macro-crate = "3"
pyo3-stub-gen = "0.22.3"
trybuild = "1"
macrotest = "1.2.1"
