[package]
name = "renamed-pyo3-user"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
doc = false

[features]
default = []
python = ["dep:py", "pyo3-gated/python"]
stub-gen = ["python", "pyo3-gated/stub-gen"]

[dependencies]
pyo3-gated = { path = "../../../crates/pyo3-gated" }
py = { package = "pyo3", version = "0.28", optional = true }
