[package]
name = "pyo3-gated"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Attribute macros to expose Rust types to Python via PyO3 from a single definition - no duplicate structs or impl blocks."
readme = "../../README.md"
keywords = ["pyo3", "python", "macros", "bindings", "codegen"]
categories = [
    "development-tools::procedural-macro-helpers",
    "api-bindings",
    "rust-patterns",
]

[features]
default = []
python = []
stub-gen = ["python", "dep:pyo3-stub-gen"]

[dependencies]
pyo3-gated-macros = { version = "=0.1.1", path = "../pyo3-gated-macros" }
pyo3-stub-gen = { workspace = true, optional = true }

[dev-dependencies]
trybuild.workspace = true
macrotest.workspace = true

[package.metadata.docs.rs]
all-features = true
