[package]
name = "facade-pyo3-user"
version = "0.0.0"
edition = "2024"
publish = false

[features]
default = []
python = ["pyo3-gated/python"]
stub-gen = ["python", "pyo3-gated/stub-gen"]
anyhow = ["python", "pyo3-gated/anyhow"]
abi3-py39 = ["python", "pyo3-gated/abi3-py39"]
abi3-py315 = ["python", "pyo3-gated/abi3-py315"]
abi3t-py315 = ["python", "pyo3-gated/abi3t-py315"]
experimental-inspect = ["python", "pyo3-gated/experimental-inspect"]

[dependencies]
pyo3-gated = { path = "../../../crates/pyo3-gated" }
anyhow = "1"
