# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Color",
    "add",
    "callback",
]

@typing.final
class Color:
    @property
    def r(self) -> builtins.int: ...
    @r.setter
    def r(self, value: builtins.int) -> None: ...
    def __new__(cls, r: builtins.int) -> Color: ...
    def red(self) -> builtins.int: ...

def add(a: builtins.int, b: builtins.int) -> builtins.int: ...

def callback(value: collections.abc.Callable) -> object: ...

